// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package render

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Login renders the ingress page. errMsg, when non-empty, surfaces a
// failure (bad credentials, session error).
func Login(errMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"ingress\"><section class=\"ingress__hero\"><header class=\"ingress__brand\"><div class=\"ingress__brand-mark\">OR</div><div class=\"ingress__brand-sub\">ORBITAL · webmail</div></header><div class=\"ingress__copy\"><div class=\"ingress__eyebrow\">Team mail terminal</div><h1 class=\"ingress__title\">Mail, projects,<br>and <em>notes</em>.</h1><p class=\"ingress__lede\">Sign in to the shared inbox to read mail, reply, tag threads into projects, bookmark for later, and keep team notes — all backed by your own IMAP server.</p></div><footer class=\"ingress__footnote\"><span><span class=\"dot is-live\"></span>&nbsp; service online</span> <span>v0.1</span></footer></section><section class=\"ingress__form-wrap\"><form class=\"ingress__form\" action=\"/login\" method=\"post\"><header class=\"ingress__form-head\"><h2>Sign in</h2><p>Enter your credentials to access the inbox.</p></header>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if errMsg != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"ingress__error\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(errMsg)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/render/login.templ`, Line: 32, Col: 42}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"ingress__field\"><label class=\"ingress__field-label\" for=\"email\"><span>Email</span></label> <input id=\"email\" name=\"email\" type=\"email\" class=\"ingress__field-input\" placeholder=\"you@example.com\" autocomplete=\"email\" required></div><div class=\"ingress__field\"><label class=\"ingress__field-label\" for=\"password\"><span>Password</span></label> <input id=\"password\" name=\"password\" type=\"password\" class=\"ingress__field-input\" placeholder=\"••••••••\" autocomplete=\"current-password\" required></div><button type=\"submit\" class=\"ingress__submit\"><span>Sign in</span> <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"><path d=\"M5 12h14M13 5l7 7-7 7\"></path></svg></button><p class=\"ingress__sig\">All connections are TLS-encrypted.</p></form></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Sign in — ORBITAL").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
